### PR TITLE
docs: add faq section about value transform

### PR DESCRIPTION
**Pull request by mucaho**
This PR adds a section to the FAQ and documents a pragmatic way of how to have values parsed and/or transformed in your `NgrxValueConverter` properly.

Resolves #168.

### CODE REVIEW

**Comment by MrWolfZ** [comment]
Hmm, let me see if I understand the problem correctly. Looking at #168 I see there is a critical assumption in value converters that is not obvious and also not documented, specifically that `convertStateToView(convertViewToState(x)) === x`. In other words, the value converter must be symmetric. This is intentional and required however. There are many issues that can occur when setting the value of an `input` while the user is typing in it (e.g. the cursor jumps to the beginning of the input etc.). The assumption above prevents these kinds of issues since it ensures the view value will never be set as a result of the view value itself changing.

Now in your example it is not exactly this situation, since you are reacting to `change`, which occurs only on `blur` and therefore the problem above doesn't apply. It is impossible to distinguish between those two scenarios from the point of view of a value converter though.

Therefore, I feel that the documentation needs to mention the assumption about value converters and the FAQ entry needs a better title, e.g. "How can I change the value of an `input` (e.g. making all text upper-case) after the user has finished typing?".

PS: I guess this was just a made-up example from #168 but you should not be using moment objects in your form state, since afaik they are not safely serializable. Instead, store the date as an ISO string in the state and transform it to Date/moment for the view value.

**Comment by mucaho** [comment]
> The _[symmetry]_ assumption above prevents these kinds of issues since it ensures the view value will never be set as a result of the view value itself changing.
> Now in your example it is not exactly this situation, since you are reacting to change, which occurs only on blur and therefore the problem above doesn't apply.

I have changed the example to respond to `(input)` events, which trigger on every keypress, and there are still no issues, due to how the implementation works.

The problem this `onInput` event listener solves with view-to-state asymmetric value converters is that the native input's value is not properly updated. With this "hack" it's updated properly, but no further form actions are propagated from the native input - the state value set by the previous, regular update through the value converter matches the state value obtained after triggering the `onInput` event listener.

------------

> For this scenario you may just want to put a method on your component to transform the value itself since you are interested in a one-way transformation instead of two-way.

Sounds like the most straightforward solution, but a first naive implementation does not work:
```html
        <input type="text"
               [ngrxFormControlState]="formState.controls.countryCode"
               (input)="$event.target.value = uppercaseTransform($event.target.value)"
               (ngrxFormsAction)="handleFormAction($event)"
               >
```
```ts
  uppercaseTransform(param: string): string {
    return param.toUpperCase();
  }
```
The problem here is that the state value is not properly updated: if I write "aaa", the input will display "AAA", but the state will contain "AAa".

To fix this, you would need something like this
```html
        <input type="text"
               [ngrxFormControlState]="formState.controls.countryCode"
               (input)="uppercaseTransform($event.target)"
               (ngrxFormsAction)="handleFormAction($event)"
               >
```
```ts
  uppercaseTransform(target: any): void {
    const uppercase = (target.value as string).toUpperCase();
    target.value = uppercase;
    this.formState = reducer(this.formState, new SetValueAction('localStateForm.countryCode', uppercase));
  }
```

---------------

How do we proceed?

**Comment by MrWolfZ** [comment]
Sorry for the late response. A couple of things to point out here.

With the `(input)` event, try placing the cursor not at the end of the input but somewhere in the middle or the beginning. You will see that the cursor jumps to the end of the input if you type something. This is one of the major issues with changing the value of an input while the user is typing. The workarounds I have used in the past are a special directive that stores the cursor position, updates the `input`'s value and then restores the cursor position.

I still believe a custom function for this (or a dedicated directive as mentioned above) is the best approach. Your code does what I would do, except that I would make it independent of **ngrx-forms**  like this:

```ts
uppercaseTransform(target: HTMLInputElement): void {
  const uppercase = target.value.toUpperCase();
  if (target.value !== uppercase) {
    target.value = uppercase;
    target.dispatchEvent(new Event('input'));
  }
}
```

This same code could be in the directive that also handles the cursor position (if that is an issue for you).

**Comment by MrWolfZ** [comment]
It seems to me this is very much an absolute edge case that is not worthy of an FAQ mention. If more issues about this pop up in the future I can add an entry like I described above.

**Pull request closed without merging**
