### PR TITLE
refactor(): update to support angular and ngrx v7

### PR DESCRIPTION
**Pull request by wbhob**
Tests and build are passing! This PR just updates dependencies to support Angular 7, for those of us waiting for the upgrade.

I recommend releasing this patch as a _major_ version.

### CODE REVIEW

**Comment by wbhob** [comment]
in case you're not watching the repo, i'll @ you

@MrWolfZ

**Comment by MrWolfZ** [comment]
Thank you for this contribution. I have re-targeted the PR to the `develop` branch. Please fix the merge conflict, then I'll merge the PR.

**Comment by wbhob** [comment]
done!

**Comment by MrWolfZ** [comment]
Ah, damn, I just made a minor release before I merge your PR and create a new major release. I didn't realize though that by updating the version number in the package-lock.json it would create another conflict. Please resolve the conflict one more time. Sorry and a happy new year.

**Comment by wbhob** [comment]
This should work. Happy new year!

**Pull request merged**
